### ISSUE TITLE
Fails to build on some non-x86 platforms

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoinconsensus#3]
Needs this upstream patch in order to build on at least powerpc: https://github.com/bitcoin/bitcoin/pull/12998

**Comment by jeandudey** [comment]
Is there something I can do about it? This is blocking me from contributing to rust-lightning because this doesn't build on my computer.

**Comment by TheBlueMatt** [comment]
It was included in 0.16.1, so bumping the subtree should fix the issue.
