### ISSUE TITLE
Tag and release - tracking issue

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoinconsensus#47]
@apoelstra this is ready to be tagged and released. In future I'll follow your suggestion and open a PR bumping the version as the release tracking issue, for this release please consider this the 'release tracking issue' since the version bump and release notes have already been done.

Thanks

**Comment by apoelstra** [comment]
Ok, I'll see if I can figure out submodules enough to publish a release..

**Comment by apoelstra** [comment]
Does anyone know a series of commands that will download the missing data from the `depend/` directory?

The README says I need to re-clone the repo, and then presumably recreate all my worktrees. That does not seem reasonable.

**Comment by tcharding** [comment]
What data is missing? I've been managing the submodule, anytime something shows up in `git status` (run in the repo root directory), by just cd'ing into it and using `git checkout`, using the hash that shows up in the output of `git status`. Then when I was updating the submodule (https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/42) I did a bunch of things in `depend`, documented on the PR.

Does that help?

**Comment by tcharding** [comment]
No need to respond in depth, I'm tackling the submodules issue and learning the pain :)

**Comment by apoelstra** [comment]
No dice.
```
12:40:41 -bash@camus ~/code/rust-bitcoin/rust-bitcoinconsensus/master b00bd50$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

The `depend/bitcoin` directory is completely empty, I can't find any way to get git to acknowledge that maybe something should be there, and none of the `git submodule` incantations the Internet have suggested have helped.

**Comment by tcharding** [comment]
Can we move to sub trees? https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/49

**Comment by tcharding** [comment]
Release was done already.
