### ISSUE TITLE
move off of submodules

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoinconsensus#48]
Submodules are a confusing and incompletely-implemented hack, which don't even work with git itself, let alone any tooling designed to work with git.

This is the only project in the rust-bitcoin ecosystem that uses submodules. We should move away from them.

**Comment by tcharding** [comment]
This was resolved by https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/51
