### ISSUE TITLE
Use `bitflags` crate to implement bit flags

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoinconsensus#58]
The crate is well-established, maintained by several Rust developers and considered idiomatic for implementing bit flags.

**Comment by apoelstra** [comment]
I like it -- but their MSRV is 1.46 unfortunately which is ahead of us.

**Comment by Kixunil** [comment]
I guess there could be an older, sufficiently good version. The macro is not rocket science and I don't expect any vulnerabilities. At worst we could fork it/copy-paste it.

**Comment by tcharding** [comment]
We don't want a dependency for something this trivial.
