### ISSUE TITLE
Manually create a newtype for bit flags with overloaded operators.

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoinconsensus#61]
Replacement of #58 

Since an external macro is not desired we could just copy it and make adjustments to support MSRV or manually expand it. It'd be best to have it as close as possible to the output of said macro because it's somewhat a standard. Consumers don't even need to know it's not used under the hood if the API is the same.

**Comment by apoelstra** [comment]
Maybe the function in question should just take a bunch of booleans?

**Comment by Kixunil** [comment]
That's not forward-compatible. But a builder would be.

**Comment by apoelstra** [comment]
Good observation.

I do think a builder (with a `try_from_u32` shortcut for people who just want to use bitflags) would be the most Rustic thing to do... and that if we're going to go into the effort of properly-typing this then we should go all the way to a builder.

**Comment by Kixunil** [comment]
So people would need to know which exact bit flags are used by `libsecp256k1` to call `try_from_u32`? Sounds like not providing it wouldn't hurt much and we could even be compatible if the underlying library breaks the API to use different values (not that I expect it to happen).

**Comment by apoelstra** [comment]
It's `libbitcoinconsensus`, not libsecp, which is taking these flags .. and yes, I would expect that somebody using the rust bindings to libbitcoinconsensus would know its quirks.

But yes, I agree it is a good API goal to make this avoidable.

**Comment by apoelstra** [comment]
I certainly don't. I think we should just finish this crate and move on.

With libbitcoinkernel we can try to make a good API.

**Comment by Kixunil** [comment]
@tcharding can't be backported since it's a newtype.

If we accept that "just use `rust-bitcoin` is the proper way to get highl-level  good API then indeed, this is not needed. But if we do want to expose the flags we really should use bitflags.

**Comment by Kixunil** [comment]
That's not how backporting works. The entire point of backporting is to add fixes to old versions **without breaking the API**. If you're breaking the API you're not backporting. Using newtypes instead of raw integers is API-breaking.

**Comment by tcharding** [comment]
Oh I must have been on crack this morning when I made that last comment, we only have the point release number - you are 100% correct.

> But if we do want to expose the flags we really should use bitflags.

I'm going to go ahead and assume this is never going to get done then because it would mean re-releasing all the core versions again - I definitely do not want to go through all that again.

**Comment by Kixunil** [comment]
> re-releasing all the core versions again

Why? Just support the change in the latest one.

**Comment by tcharding** [comment]
This crate is about to be EOL'd, I don't see a reason to have support for this in one of them only when the idea is that the last 3 or 4 are meant to be used by folk that want a particular version of Core.

**Comment by apoelstra** [comment]
Agreed with "about to be EOL'd, let's not try to improve the API in half-hearted ways".

But FWIW I think it's pretty niche for people to want to use a specific non-latest version of Core. In my mind the reason that we did independent releases for all of them was for symmetry and possibly to help people upgrading so that they wouldn't need to jump too many versions at once.

**Comment by Kixunil** [comment]
> This crate is about to be EOL'd

Whaat? Where was this decided? I didn't notice...

**Comment by apoelstra** [comment]
@Kixunil in https://github.com/bitcoin/bitcoin/pull/29189

**Comment by apoelstra** [comment]
I think we should just encapsulate it in rust-bitcoin so that it won't be visible when we swap it out for `libbitcoinkernel` or whatever.

The upstream deprecation really doesn't matter until there is some actual consensus change in Bitcoin.

**Comment by Kixunil** [comment]
> `libbitcoinkernel`

That one is stateful which is a huge can of worms.

> The upstream deprecation really doesn't matter until there is some actual consensus change in Bitcoin.

But then it will be too late for people who use it.
